#include <sys/syslog.h>
int main(int argc, char **argv)
{
    openlog("MyMsgMARK", LOG_CONS | LOG_PID | LOG_PERROR | LOG_NDELAY | LOG_PERROR, 0);
    // LOG_USER
    syslog(LOG_NOTICE,
           "This is a syslog test message generated by program '%s'/n",
           argv[0]);
    closelog();
    return 0;
}